[package]
name = "epitech-ics"
version = "0.1.0"
authors = ["Philippe Loctaux <p@philippeloctaux.com>"]
edition = "2018"

[dependencies]
actix-web = "2.0.0"
actix-rt = "1.1.1"
chrono = "0.4.15"
uuid = { version = "0.8.1", features = ["v4"] }
reqwest = "0.10.8"
serde_json = "1.0.57"
env_logger = "0.7.1"
log = "0.4.11"
regex = "1.3.9"
epitok = "0.2.0"
ics = "0.4.2"